name: ci

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:

env:
  MG_DEBUG: false
  DEVELOPER_NODE: 1

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.13', '1.14', '1.15']
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          go get -v github.com/google/go-querystring/query
          go get -v github.com/stretchr/testify/assert
          go get -v github.com/joho/godotenv
          go get -v github.com/h2non/gock
          cp .env.dist .env
      - name: Tests
        run: go test -v ./... -cover -coverprofile=coverage.txt -covermode=atomic
      - name: Coverage
        run: bash <(curl -s https://codecov.io/bash)
